apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: final
  name: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final
  template:
    metadata:
      labels:
        app: final
    spec:
      containers:
      - image: ahmedsalah3717/finalproject:${BUILD_NUMBER}
        name: final
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
