
apiVersion: v1
kind: Service
metadata:
  labels:
    app: final
  name: final
spec:
  ports:
  - name: finalport
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: final
  type: LoadBalancer
status:
  loadBalancer: {}
