pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/your/repo.git'
            }
        }

        stage('Build image') {
            steps {
                sh 'docker build -t your-docker-username/your-image-name .'
            }
        }

        stage('Push image') {
            steps {
                withCredentials([string(credentialsId: 'your-dockerhub-creds-id', variable: 'DOCKERHUB_CREDS')]) {
                    sh 'echo $DOCKERHUB_CREDS | docker login -u your-docker-username --password-stdin'
                    sh 'docker push your-docker-username/your-image-name'
                }
            }
        }
    }
}

